/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  AuthErrorMessage,
  ChangePasswordInput,
  ConfirmOrderBody,
  CreatePaymentIntentBody,
  ErrorMessage,
  GameObject,
  GamesArray,
  GetGamesParams,
  OrderItemObject,
  OrderObject,
  OrdersArray,
  PaymentIntentResponse,
  SuccessMessage,
  UpdateNameInput,
  UpdateNameResponse,
  UserCredentials,
  UserObject,
  UsersArray
} from '../../model'
import { customInstance } from '../../../instance';
import type { ErrorType, BodyType } from '../../../instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary List all users
 */
export const getUsers = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UsersArray>(
      {url: `/users`, method: 'GET', signal
    },
      options);
    }
  

export const getGetUsersQueryKey = () => {
    return [`/users`] as const;
    }

    
export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<AuthErrorMessage | ErrorMessage>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = ErrorType<AuthErrorMessage | ErrorMessage>

/**
 * @summary List all users
 */
export const useGetUsers = <TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<AuthErrorMessage | ErrorMessage>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetUsersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update the current user's display name
 */
export const updateName = (
    updateNameInput: BodyType<UpdateNameInput>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateNameResponse>(
      {url: `/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateNameInput
    },
      options);
    }
  


export const getUpdateNameMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateName>>, TError,{data: BodyType<UpdateNameInput>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateName>>, TError,{data: BodyType<UpdateNameInput>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateName>>, {data: BodyType<UpdateNameInput>}> = (props) => {
          const {data} = props ?? {};

          return  updateName(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateNameMutationResult = NonNullable<Awaited<ReturnType<typeof updateName>>>
    export type UpdateNameMutationBody = BodyType<UpdateNameInput>
    export type UpdateNameMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Update the current user's display name
 */
export const useUpdateName = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateName>>, TError,{data: BodyType<UpdateNameInput>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof updateName>>,
        TError,
        {data: BodyType<UpdateNameInput>},
        TContext
      > => {

      const mutationOptions = getUpdateNameMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Change the current user's password
 */
export const changePassword = (
    changePasswordInput: BodyType<ChangePasswordInput>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessMessage>(
      {url: `/users/me/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordInput
    },
      options);
    }
  


export const getChangePasswordMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordInput>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordInput>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: BodyType<ChangePasswordInput>}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = BodyType<ChangePasswordInput>
    export type ChangePasswordMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Change the current user's password
 */
export const useChangePassword = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: BodyType<ChangePasswordInput>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: BodyType<ChangePasswordInput>},
        TContext
      > => {

      const mutationOptions = getChangePasswordMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary List up to 10 games with the highest discount, discount > 0, highest first
 */
export const getGamesTopDeals = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GameObject[]>(
      {url: `/games/top-deals`, method: 'GET', signal
    },
      options);
    }
  

export const getGetGamesTopDealsQueryKey = () => {
    return [`/games/top-deals`] as const;
    }

    
export const getGetGamesTopDealsQueryOptions = <TData = Awaited<ReturnType<typeof getGamesTopDeals>>, TError = ErrorType<ErrorMessage>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGamesTopDeals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGamesTopDealsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGamesTopDeals>>> = ({ signal }) => getGamesTopDeals(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGamesTopDeals>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGamesTopDealsQueryResult = NonNullable<Awaited<ReturnType<typeof getGamesTopDeals>>>
export type GetGamesTopDealsQueryError = ErrorType<ErrorMessage>

/**
 * @summary List up to 10 games with the highest discount, discount > 0, highest first
 */
export const useGetGamesTopDeals = <TData = Awaited<ReturnType<typeof getGamesTopDeals>>, TError = ErrorType<ErrorMessage>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGamesTopDeals>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetGamesTopDealsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List games in paged format from db
 */
export const getGames = (
    page: number,
    params?: GetGamesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GamesArray>(
      {url: `/games/${page}`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetGamesQueryKey = (page: number,
    params?: GetGamesParams,) => {
    return [`/games/${page}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetGamesQueryOptions = <TData = Awaited<ReturnType<typeof getGames>>, TError = ErrorType<ErrorMessage>>(page: number,
    params?: GetGamesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGamesQueryKey(page,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGames>>> = ({ signal }) => getGames(page,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(page), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGames>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGamesQueryResult = NonNullable<Awaited<ReturnType<typeof getGames>>>
export type GetGamesQueryError = ErrorType<ErrorMessage>

/**
 * @summary List games in paged format from db
 */
export const useGetGames = <TData = Awaited<ReturnType<typeof getGames>>, TError = ErrorType<ErrorMessage>>(
 page: number,
    params?: GetGamesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGames>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetGamesQueryOptions(page,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Fetch game by id
 */
export const getGame = (
    gameId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GameObject>(
      {url: `/game/${gameId}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetGameQueryKey = (gameId: number,) => {
    return [`/game/${gameId}`] as const;
    }

    
export const getGetGameQueryOptions = <TData = Awaited<ReturnType<typeof getGame>>, TError = ErrorType<ErrorMessage>>(gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGame>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameQueryKey(gameId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGame>>> = ({ signal }) => getGame(gameId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gameId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGame>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGameQueryResult = NonNullable<Awaited<ReturnType<typeof getGame>>>
export type GetGameQueryError = ErrorType<ErrorMessage>

/**
 * @summary Fetch game by id
 */
export const useGetGame = <TData = Awaited<ReturnType<typeof getGame>>, TError = ErrorType<ErrorMessage>>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGame>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetGameQueryOptions(gameId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Register a new user
 */
export const register = (
    userCredentials: BodyType<UserCredentials>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UserObject>(
      {url: `/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCredentials
    },
      options);
    }
  


export const getRegisterMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<UserCredentials>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<UserCredentials>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: BodyType<UserCredentials>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = BodyType<UserCredentials>
    export type RegisterMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Register a new user
 */
export const useRegister = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<UserCredentials>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: BodyType<UserCredentials>},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Login an existing user
 */
export const login = (
    userCredentials: BodyType<UserCredentials>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UserObject>(
      {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCredentials
    },
      options);
    }
  


export const getLoginMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<UserCredentials>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<UserCredentials>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<UserCredentials>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<UserCredentials>
    export type LoginMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Login an existing user
 */
export const useLogin = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<UserCredentials>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<UserCredentials>},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Logout the current user
 */
export const logout = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SuccessMessage>(
      {url: `/logout`, method: 'GET', signal
    },
      options);
    }
  

export const getLogoutQueryKey = () => {
    return [`/logout`] as const;
    }

    
export const getLogoutQueryOptions = <TData = Awaited<ReturnType<typeof logout>>, TError = ErrorType<ErrorMessage>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logout>>> = ({ signal }) => logout(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData> & { queryKey: QueryKey }
}

export type LogoutQueryResult = NonNullable<Awaited<ReturnType<typeof logout>>>
export type LogoutQueryError = ErrorType<ErrorMessage>

/**
 * @summary Logout the current user
 */
export const useLogout = <TData = Awaited<ReturnType<typeof logout>>, TError = ErrorType<ErrorMessage>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getLogoutQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary List every order placed by the current user, newest first
 */
export const getOrders = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrdersArray>(
      {url: `/orders`, method: 'GET', signal
    },
      options);
    }
  

export const getGetOrdersQueryKey = () => {
    return [`/orders`] as const;
    }

    
export const getGetOrdersQueryOptions = <TData = Awaited<ReturnType<typeof getOrders>>, TError = ErrorType<ErrorMessage>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrders>>> = ({ signal }) => getOrders(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrdersQueryResult = NonNullable<Awaited<ReturnType<typeof getOrders>>>
export type GetOrdersQueryError = ErrorType<ErrorMessage>

/**
 * @summary List every order placed by the current user, newest first
 */
export const useGetOrders = <TData = Awaited<ReturnType<typeof getOrders>>, TError = ErrorType<ErrorMessage>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOrdersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create a Stripe PaymentIntent for the given cart items, server-priced
 */
export const createPaymentIntent = (
    createPaymentIntentBody: BodyType<CreatePaymentIntentBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PaymentIntentResponse>(
      {url: `/orders/payment-intent`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPaymentIntentBody
    },
      options);
    }
  


export const getCreatePaymentIntentMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPaymentIntent>>, TError,{data: BodyType<CreatePaymentIntentBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createPaymentIntent>>, TError,{data: BodyType<CreatePaymentIntentBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPaymentIntent>>, {data: BodyType<CreatePaymentIntentBody>}> = (props) => {
          const {data} = props ?? {};

          return  createPaymentIntent(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePaymentIntentMutationResult = NonNullable<Awaited<ReturnType<typeof createPaymentIntent>>>
    export type CreatePaymentIntentMutationBody = BodyType<CreatePaymentIntentBody>
    export type CreatePaymentIntentMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Create a Stripe PaymentIntent for the given cart items, server-priced
 */
export const useCreatePaymentIntent = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPaymentIntent>>, TError,{data: BodyType<CreatePaymentIntentBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof createPaymentIntent>>,
        TError,
        {data: BodyType<CreatePaymentIntentBody>},
        TContext
      > => {

      const mutationOptions = getCreatePaymentIntentMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Confirm a succeeded PaymentIntent and create the order, with one activation code per digital game
 */
export const confirmOrder = (
    confirmOrderBody: BodyType<ConfirmOrderBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<OrderObject>(
      {url: `/orders/confirm`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: confirmOrderBody
    },
      options);
    }
  


export const getConfirmOrderMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmOrder>>, TError,{data: BodyType<ConfirmOrderBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof confirmOrder>>, TError,{data: BodyType<ConfirmOrderBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmOrder>>, {data: BodyType<ConfirmOrderBody>}> = (props) => {
          const {data} = props ?? {};

          return  confirmOrder(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmOrderMutationResult = NonNullable<Awaited<ReturnType<typeof confirmOrder>>>
    export type ConfirmOrderMutationBody = BodyType<ConfirmOrderBody>
    export type ConfirmOrderMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Confirm a succeeded PaymentIntent and create the order, with one activation code per digital game
 */
export const useConfirmOrder = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmOrder>>, TError,{data: BodyType<ConfirmOrderBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof confirmOrder>>,
        TError,
        {data: BodyType<ConfirmOrderBody>},
        TContext
      > => {

      const mutationOptions = getConfirmOrderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Fetch an order placed by the current user
 */
export const getOrder = (
    orderId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrderObject>(
      {url: `/orders/${orderId}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetOrderQueryKey = (orderId: number,) => {
    return [`/orders/${orderId}`] as const;
    }

    
export const getGetOrderQueryOptions = <TData = Awaited<ReturnType<typeof getOrder>>, TError = ErrorType<ErrorMessage>>(orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrderQueryKey(orderId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrder>>> = ({ signal }) => getOrder(orderId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(orderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrderQueryResult = NonNullable<Awaited<ReturnType<typeof getOrder>>>
export type GetOrderQueryError = ErrorType<ErrorMessage>

/**
 * @summary Fetch an order placed by the current user
 */
export const useGetOrder = <TData = Awaited<ReturnType<typeof getOrder>>, TError = ErrorType<ErrorMessage>>(
 orderId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrder>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getGetOrderQueryOptions(orderId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Mark one purchased game in an order as activated by the user
 */
export const activateOrderItem = (
    orderId: number,
    itemId: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<OrderItemObject>(
      {url: `/orders/${orderId}/items/${itemId}/activate`, method: 'PATCH'
    },
      options);
    }
  


export const getActivateOrderItemMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateOrderItem>>, TError,{orderId: number;itemId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activateOrderItem>>, TError,{orderId: number;itemId: number}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateOrderItem>>, {orderId: number;itemId: number}> = (props) => {
          const {orderId,itemId} = props ?? {};

          return  activateOrderItem(orderId,itemId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ActivateOrderItemMutationResult = NonNullable<Awaited<ReturnType<typeof activateOrderItem>>>
    
    export type ActivateOrderItemMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Mark one purchased game in an order as activated by the user
 */
export const useActivateOrderItem = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateOrderItem>>, TError,{orderId: number;itemId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof activateOrderItem>>,
        TError,
        {orderId: number;itemId: number},
        TContext
      > => {

      const mutationOptions = getActivateOrderItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Refresh token
 */
export const refresh = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UserObject>(
      {url: `/refresh`, method: 'GET', signal
    },
      options);
    }
  

export const getRefreshQueryKey = () => {
    return [`/refresh`] as const;
    }

    
export const getRefreshQueryOptions = <TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorType<ErrorMessage | AuthErrorMessage>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRefreshQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof refresh>>> = ({ signal }) => refresh(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData> & { queryKey: QueryKey }
}

export type RefreshQueryResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
export type RefreshQueryError = ErrorType<ErrorMessage | AuthErrorMessage>

/**
 * @summary Refresh token
 */
export const useRefresh = <TData = Awaited<ReturnType<typeof refresh>>, TError = ErrorType<ErrorMessage | AuthErrorMessage>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getRefreshQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



