/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  PostLogin200,
  PostLogin400,
  PostLoginBody,
  PostLogout200,
  PostLogout401,
  PostRegister201,
  PostRegister400,
  PostRegister500,
  PostRegisterBody
} from '../../model'
import { customInstance } from '../../../instance';
import type { ErrorType, BodyType } from '../../../instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Register a new user
 */
export const postRegister = (
    postRegisterBody: BodyType<PostRegisterBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PostRegister201>(
      {url: `/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRegisterBody
    },
      options);
    }
  


export const getPostRegisterMutationOptions = <TError = ErrorType<PostRegister400 | PostRegister500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: BodyType<PostRegisterBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: BodyType<PostRegisterBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRegister>>, {data: BodyType<PostRegisterBody>}> = (props) => {
          const {data} = props ?? {};

          return  postRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postRegister>>>
    export type PostRegisterMutationBody = BodyType<PostRegisterBody>
    export type PostRegisterMutationError = ErrorType<PostRegister400 | PostRegister500>

    /**
 * @summary Register a new user
 */
export const usePostRegister = <TError = ErrorType<PostRegister400 | PostRegister500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: BodyType<PostRegisterBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postRegister>>,
        TError,
        {data: BodyType<PostRegisterBody>},
        TContext
      > => {

      const mutationOptions = getPostRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Login an existing user
 */
export const postLogin = (
    postLoginBody: BodyType<PostLoginBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PostLogin200>(
      {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postLoginBody
    },
      options);
    }
  


export const getPostLoginMutationOptions = <TError = ErrorType<PostLogin400>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: BodyType<PostLoginBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: BodyType<PostLoginBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: BodyType<PostLoginBody>}> = (props) => {
          const {data} = props ?? {};

          return  postLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
    export type PostLoginMutationBody = BodyType<PostLoginBody>
    export type PostLoginMutationError = ErrorType<PostLogin400>

    /**
 * @summary Login an existing user
 */
export const usePostLogin = <TError = ErrorType<PostLogin400>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: BodyType<PostLoginBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postLogin>>,
        TError,
        {data: BodyType<PostLoginBody>},
        TContext
      > => {

      const mutationOptions = getPostLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Logout the current user
 */
export const postLogout = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PostLogout200>(
      {url: `/logout`, method: 'POST'
    },
      options);
    }
  


export const getPostLogoutMutationOptions = <TError = ErrorType<PostLogout401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogout>>, void> = () => {
          

          return  postLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postLogout>>>
    
    export type PostLogoutMutationError = ErrorType<PostLogout401>

    /**
 * @summary Logout the current user
 */
export const usePostLogout = <TError = ErrorType<PostLogout401>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    