openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Dionis
  license:
    name: MIT
servers:
  - url: http://dionis.swagger.io/v1
paths:
  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: A paged array of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/usersArray'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
      security:
        - bearerHttpAuthentication: []
  /user/delete:
    post:
      summary: Delete user
      operationId: deleteUser
      tags:
        - deleteUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: User deleted!
      responses:
        '200':
          description: An object with success message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successMessage'
        '400':
          description: Bad request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
      security:
        - bearerHttpAuthentication: []
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userCredentials'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userObject'

        '400':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
  /login:
    post:
      summary: Login an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userCredentials'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userObject'
        '400':
          description: User does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
  /logout:
    post:
      summary: Logout the current user
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/successMessage'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorMessage'
      security:
        - bearerHttpAuthentication: []
components:
  securitySchemes:
    bearerHttpAuthentication:
      description: Bearer token using a JWT
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    errorMessage:
      type: object
      properties:
        message:
          type: string
          example: No token provided
      description: A text message describing an error
    userObject:
      type: object
      properties:
        message:
          type: string
          example: User logged in successfully!
        accessToken:
          type: string
    successMessage:
      type: object
      properties:
        message:
          type: string
          example: User logged out successfully!
    usersArray:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          email:
            type: string
            format: email
          name:
            type: string
          password:
            type: string
          refreshToken:
            type: string
            nullable: true
          role:
            type: integer
            enum: [101, 500, 233]
          createdAt:
            type: string
            format: date
    userCredentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password
