/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query'
import type {
  InfiniteData,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  Error,
  UsersArray
} from '../../model'
import { customInstance } from '../../../instance';
import type { ErrorType } from '../../../instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Delete all users
 */
export const deleteUsers = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UsersArray>(
      {url: `/users/deleteAll`, method: 'GET', signal
    },
      options);
    }
  

export const getDeleteUsersQueryKey = () => {
    return [`/users/deleteAll`] as const;
    }

    
export const getDeleteUsersInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof deleteUsers>>>, TError = ErrorType<Error>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof deleteUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteUsers>>> = ({ signal }) => deleteUsers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof deleteUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type DeleteUsersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof deleteUsers>>>
export type DeleteUsersInfiniteQueryError = ErrorType<Error>

/**
 * @summary Delete all users
 */
export const useDeleteUsersInfinite = <TData = InfiniteData<Awaited<ReturnType<typeof deleteUsers>>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof deleteUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDeleteUsersInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getDeleteUsersQueryOptions = <TData = Awaited<ReturnType<typeof deleteUsers>>, TError = ErrorType<Error>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteUsers>>> = ({ signal }) => deleteUsers(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type DeleteUsersQueryResult = NonNullable<Awaited<ReturnType<typeof deleteUsers>>>
export type DeleteUsersQueryError = ErrorType<Error>

/**
 * @summary Delete all users
 */
export const useDeleteUsers = <TData = Awaited<ReturnType<typeof deleteUsers>>, TError = ErrorType<Error>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const queryOptions = getDeleteUsersQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



