/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  UsersArray
} from '../../model'

export const getDeleteUsersResponseMock = (): UsersArray => ({})


export const getDeleteUsersMockHandler = (overrideResponse?: UsersArray | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UsersArray> | UsersArray)) => {
  return http.get('*/users/deleteAll', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getDeleteUsersResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getDeleteUsersMock = () => [
  getDeleteUsersMockHandler()
]
