/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  SuccessMessage
} from '../../model'

export const getDeleteUserResponseMock = (overrideResponse: Partial< SuccessMessage > = {}): SuccessMessage => ({message: faker.helpers.arrayElement([faker.word.sample(), undefined]), ...overrideResponse})


export const getDeleteUserMockHandler = (overrideResponse?: SuccessMessage | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SuccessMessage> | SuccessMessage)) => {
  return http.post('*/user/delete', async (info) => {await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getDeleteUserResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getDeleteUserMock = () => [
  getDeleteUserMockHandler()
]
