/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  DeleteUserBody,
  ErrorMessage,
  SuccessMessage
} from '../../model'
import { customInstance } from '../../../instance';
import type { ErrorType, BodyType } from '../../../instance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Delete user
 */
export const deleteUser = (
    deleteUserBody: BodyType<DeleteUserBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<SuccessMessage>(
      {url: `/user/delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deleteUserBody
    },
      options);
    }
  


export const getDeleteUserMutationOptions = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: BodyType<DeleteUserBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: BodyType<DeleteUserBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {data: BodyType<DeleteUserBody>}> = (props) => {
          const {data} = props ?? {};

          return  deleteUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    export type DeleteUserMutationBody = BodyType<DeleteUserBody>
    export type DeleteUserMutationError = ErrorType<ErrorMessage>

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = ErrorType<ErrorMessage>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{data: BodyType<DeleteUserBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {data: BodyType<DeleteUserBody>},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    