/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOrderObject } from './adminOrderObject';

export interface AdminOrdersPage {
  items: AdminOrderObject[];
  page: number;
  pageSize: number;
  total: number;
}
