/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { OrderObject } from './orderObject';
import type { AdminOrderObjectAllOf } from './adminOrderObjectAllOf';

export type AdminOrderObject = OrderObject & AdminOrderObjectAllOf;
