/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { AuthErrorMessageUser } from './authErrorMessageUser';

/**
 * An object with text message describing an error and nullable user
 */
export interface AuthErrorMessage {
  message?: string;
  /** @nullable */
  user?: AuthErrorMessageUser;
}
