/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type AuthErrorMessageUser = { [key: string]: any } | null;
