/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { ShippingAddressInput } from './shippingAddressInput';

export type ConfirmOrderBody = {
  paymentIntentId: string;
  shippingAddress?: ShippingAddressInput;
};
