/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface EditionUpdateInput {
  description?: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  discount?: number;
  name?: string;
  /** @minimum 0 */
  price?: number;
  /** @minimum 0 */
  stock?: number;
}
