/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

/**
 * A text message describing an error
 */
export interface ErrorMessage {
  message?: string;
}
