/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GameObject } from './gameObject';
import type { GameDetailObjectAllOf } from './gameDetailObjectAllOf';

/**
 * A game with the average rating and the count of the store's own reviews
 */
export type GameDetailObject = GameObject & GameDetailObjectAllOf;
