/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GamesArrayGamesItem = {
  developer?: string;
  freetogame_profile_url?: string;
  game_url?: string;
  genre?: string;
  id?: number;
  platform?: string;
  price?: number;
  publisher?: string;
  rating?: string;
  release_date?: string;
  short_description?: string;
  thumbnail?: string;
  title?: string;
};
