/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface GameEditionObject {
  description: string;
  discount: number;
  id: number;
  name: string;
  price: number;
  stock: number;
}
