/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GameWithReviewSummaryAllOf = {
  /**
   * The average review rating rounded to one decimal, or null when the game has no review
   * @nullable
   */
  averageRating: number | null;
  reviewCount: number;
};
