/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GamesArrayGamesItem } from './gamesArrayGamesItem';

export interface GamesArray {
  games?: GamesArrayGamesItem[];
  totalPages?: number;
}
