/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GameObject } from './gameObject';

export interface GamesArray {
  games?: GameObject[];
  totalPages?: number;
}
