/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface GameInput {
  developer: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  discount: number;
  freetogame_profile_url: string;
  game_url: string;
  genre: string;
  /** Only the seed script sends one */
  id?: number;
  platform: string;
  /** @minimum 0 */
  price: number;
  publisher: string;
  rating: string;
  release_date: string;
  short_description: string;
  thumbnail: string;
  title: string;
}
