/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GetAdminOrdersParams = {
page?: number;
pageSize?: number;
/**
 * Case-insensitive fragment of the customer email
 */
email?: string;
};
