/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GetGamesPlatform = typeof GetGamesPlatform[keyof typeof GetGamesPlatform];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetGamesPlatform = {
  PC: 'PC',
  PS5: 'PS5',
  Xbox: 'Xbox',
  Switch: 'Switch',
} as const;
