/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GetGamesEdition = typeof GetGamesEdition[keyof typeof GetGamesEdition];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetGamesEdition = {
  digital: 'digital',
  standard: 'standard',
  collector: 'collector',
} as const;
