/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GetGamesPlatform } from './getGamesPlatform';
import type { GetGamesSort } from './getGamesSort';
import type { GetGamesEdition } from './getGamesEdition';

export type GetGamesParams = {
/**
 * Case-insensitive title fragment to filter by
 */
search?: string;
/**
 * Platform to filter by (matches games whose platform contains this value)
 */
platform?: GetGamesPlatform;
/**
 * Sort order to apply before pagination
 */
sort?: GetGamesSort;
/**
 * Edition to filter by. Digital matches every game; standard/collector match games with a physical edition whose name contains that word.
 */
edition?: GetGamesEdition;
/**
 * Exact genre, one of the values from /games/genres
 */
genre?: string;
/**
 * Lowest discounted price in whole euros, inclusive
 */
minPrice?: number;
/**
 * Highest discounted price in whole euros, inclusive
 */
maxPrice?: number;
};
