/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GetGameReviewsParams = {
/**
 * The page number, starting at 1
 */
page?: number;
};
