/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GetGamesPlatform } from './getGamesPlatform';
import type { GetGamesSort } from './getGamesSort';

export type GetGamesParams = {
/**
 * Case-insensitive title fragment to filter by
 */
search?: string;
/**
 * Platform to filter by (matches games whose platform contains this value)
 */
platform?: GetGamesPlatform;
/**
 * Sort order to apply before pagination
 */
sort?: GetGamesSort;
};
