/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type GetGamesSort = typeof GetGamesSort[keyof typeof GetGamesSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetGamesSort = {
  price_asc: 'price_asc',
  price_desc: 'price_desc',
  rating_desc: 'rating_desc',
} as const;
