/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface GuestWishlistItemInput {
  /** Milliseconds since the epoch */
  addedAt?: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  discount: number;
  gameId: number;
}
