/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { Review } from './review';
import type { LinkedReviewAllOf } from './linkedReviewAllOf';

/**
 * A review with the id of its game
 */
export type LinkedReview = Review & LinkedReviewAllOf;
