/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GuestWishlistItemInput } from './guestWishlistItemInput';

export type MergeWishlistBody = {
  items: GuestWishlistItemInput[];
};
