/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { Notification } from './notification';

export interface NotificationsResponse {
  notifications: Notification[];
  /** The count of all unread notifications, also those beyond the list */
  unreadCount: number;
}
