/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationType } from './notificationType';

export interface Notification {
  actorName: string;
  createdAt: string;
  gameId: number;
  gameTitle: string;
  id: number;
  reviewId: number;
  type: NotificationType;
}
