/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemObject } from './orderItemObject';

export interface OrderObject {
  createdAt?: string;
  id?: number;
  items?: OrderItemObject[];
  stripePaymentIntentId?: string;
  /** Total actually charged, in cents */
  totalPrice?: number;
  userId?: number;
}
