/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface OrderItemInput {
  /**
   * A physical edition's id, or omitted/null for the digital purchase
   * @nullable
   */
  editionId?: number | null;
  gameId: number;
  quantity: number;
}
