/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { GameObject } from './gameObject';

export interface OrderItemObject {
  activated?: boolean;
  /** @nullable */
  activatedAt?: string | null;
  activationCode?: string;
  game?: GameObject;
  gameId?: number;
  id?: number;
  /** Unit price actually charged, in cents */
  price?: number;
  quantity?: number;
}
