/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { OrderObject } from './orderObject';

export interface OrdersPage {
  items: OrderObject[];
  page: number;
  pageSize: number;
  total: number;
}
