/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface OwnReview {
  body: string;
  createdAt: string;
  id: number;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
  updatedAt: string;
}
