/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentIntentResponse {
  /** Amount in cents, matching what Stripe charges */
  amount?: number;
  clientSecret?: string;
  paymentIntentId?: string;
}
