/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { PostLogin200User } from './postLogin200User';

export type PostLogin200 = {
  message?: string;
  user?: PostLogin200User;
};
