/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type PostRegisterBody = {
  email: string;
  password: string;
  role?: number;
};
