/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { PostRegister201User } from './postRegister201User';

export type PostRegister201 = {
  message?: string;
  user?: PostRegister201User;
};
