/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface Reply {
  authorName: string;
  body: string;
  createdAt: string;
  id: number;
}
