/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface ReplyInput {
  /**
   * @minLength 1
   * @maxLength 500
   */
  body: string;
}
