/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface ReviewInput {
  /** @maxLength 1000 */
  body?: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
}
