/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export interface ShippingAddressInput {
  shippingCity: string;
  shippingCountry: string;
  shippingLine1: string;
  shippingLine2?: string;
  shippingName: string;
  shippingPostalCode: string;
}
