/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type UsersArrayItemRole = typeof UsersArrayItemRole[keyof typeof UsersArrayItemRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersArrayItemRole = {
  NUMBER_101: 101,
  NUMBER_500: 500,
  NUMBER_233: 233,
} as const;
