/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { UserObjectUser } from './userObjectUser';

export interface UserObject {
  message?: string;
  user?: UserObjectUser;
}
