/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { UsersArrayItemRole } from './usersArrayItemRole';

export type UsersArrayItem = {
  createdAt?: string;
  email?: string;
  id?: number;
  name?: string;
  password?: string;
  /** @nullable */
  refreshToken?: string | null;
  role?: UsersArrayItemRole;
};
