/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */

export type WishlistItemObjectGame = {
  discount: number;
  id: number;
  platform: string;
  price: number;
  rating: string;
  thumbnail: string;
  title: string;
};
