/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Swagger Dionis
 * OpenAPI spec version: 1.0.0
 */
import type { WishlistItemObjectGame } from './wishlistItemObjectGame';

export interface WishlistItemObject {
  createdAt: string;
  /** The game's discount when it was added, or when the price-drop badge last showed */
  discountSnapshot: number;
  game: WishlistItemObjectGame;
  gameId: number;
}
