services:
  dionis:
    image: postgres:15
    container_name: dionis_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dionis_db
    volumes:
      - dionis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dionis_network
    restart: unless-stopped

  api:
    build:
      context: ../..
      dockerfile: apps/api/Dockerfile
    container_name: dionis_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://root:root@dionis:5432/dionis_db
    ports:
      - "3500:3500"
    depends_on:
      - dionis
    networks:
      - dionis_network
    restart: unless-stopped

volumes:
  dionis_data:

networks:
  dionis_network:
