name: Build and Test on PR

# Triggers the workflow on pull request events
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.7.3'

      # Install dependencies
      - name: Install pnpm
        run: npm i -g pnpm@8.5.0
        displayName: Install pnpm package


      - name: Install dependencies
        run: pnpm install
        displayName: Install packages

      # Run build command
      - name: Build the project
        run: pnpm build
        displayName: Build project

      # Run tests
      - name: Run tests for web
        run: pnpm test --filter web
        displayName: Rub tests for web
